FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["CatLife.API/CatLife.API.csproj", "CatLife.API/"]
COPY ["CatLife.Application/CatLife.Application.csproj", "CatLife.Application/"]
COPY ["CatLife.Domain/CatLife.Domain.csproj", "CatLife.Domain/"]
COPY ["CatLife.Infrastructure/CatLife.Infrastructure.csproj", "CatLife.Infrastructure/"]

RUN dotnet restore "CatLife.API/CatLife.API.csproj"

COPY . .
WORKDIR "/src/CatLife.API"
RUN dotnet publish "CatLife.API.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

RUN apt-get update && apt-get install -y libgssapi-krb5-2 ca-certificates curl && rm -rf /var/lib/apt/lists/*

COPY --from=build /app/publish .
EXPOSE 8080
ENTRYPOINT ["dotnet", "CatLife.API.dll"]